from pathlib import Path

path = Path(r"apps/web/app/admin/content/blog/BlogEditor.jsx")
text = path.read_text()

old_block = "              <div className=\"space-y-2\">\r\n                <label className=\"text-sm font-medium text-gray-700\">Hero image URL</label>\r\n                <input\r\n                  type=\"url\"\r\n                  value={form.coverImage}\r\n                  onChange={(event) => handleFieldChange('coverImage', event.target.value)}\r\n                  placeholder=\"https://...\"\r\n                  className=\"w-full rounded-lg border border-gray-300 px-4 py-2 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/40\"\r\n                />\r\n                {form.coverImage && (\r\n                  <div className=\"overflow-hidden rounded-lg border border-gray-200\">\r\n                    <img src={form.coverImage} alt=\"Cover preview\" className=\"w-full h-48 object-cover\" />\r\n                  </div>\r\n                )}\r\n              </div>\r\n\r\n"

if old_block not in text:
    raise SystemExit('Cover image block not found')

new_block = "              <div className=\"space-y-3\">\r\n                <div className=\"flex items-center justify-between\">\r\n                  <label className=\"text-sm font-medium text-gray-700\">Hero image</label>\r\n                  <Button\r\n                    type=\"button\"\r\n                    size=\"sm\"\r\n                    variant=\"secondary\"\r\n                    onClick={() => setShowCoverUploader((prev) => !prev)}\r\n                  >\r\n                    {showCoverUploader ? 'Close uploader' : 'Upload image'}\r\n                  </Button>\r\n                </div>\r\n                <input\r\n                  type=\"url\"\r\n                  value={form.coverImage}\r\n                  onChange={(event) => handleFieldChange('coverImage', event.target.value)}\r\n                  placeholder=\"https://...\"\r\n                  className=\"w-full rounded-lg border border-gray-300 px-4 py-2 focus:border-blue-500 focus:outline-none focus:ring-2 focus:ring-blue-500/40\"\r\n                />\r\n                <p className=\"text-xs text-gray-500\">Paste an image link or upload a file below.</p>\r\n                {showCoverUploader && (\r\n                  <div className=\"rounded-lg border border-dashed border-gray-300 bg-gray-50 p-4\">\r\n                    <ImageUploader\r\n                      onImageUploaded={(imageUrl) => {\r\n                        handleFieldChange('coverImage', imageUrl);\r\n                        setShowCoverUploader(false);\r\n                      }}\r\n                    />\r\n                  </div>\r\n                )}\r\n                {form.coverImage && (\r\n                  <div className=\"overflow-hidden rounded-lg border border-gray-200\">\r\n                    <img src={form.coverImage} alt=\"Cover preview\" className=\"w-full h-48 object-cover\" />\r\n                  </div>\r\n                )}\r\n              </div>\r\n\r\n"

text = text.replace(old_block, new_block, 1)

path.write_text(text)
